branch-defaults:
  master:
    environment: django-env2
    group_suffix: null
global:
  application_name: countur
  default_ec2_keyname: null
  default_platform: python3.4
  default_region: us-west-2
  profile: eb-cli
  sc: git
