# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('created', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='count',
            name='counter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.Counter'),
        ),
    ]
