# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 15:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='count',
            name='created',
        ),
        migrations.AddField(
            model_name='count',
            name='createdd',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 23, 15, 19, 51, 226702, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
    ]
