# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 15:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counter', '0003_auto_20160423_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='counters', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
