# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-04 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_counter_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='count',
            options={'ordering': ['-created']},
        ),
    ]
